Repository Museum-Mate/museum-mate-be, pull requests merged in 2023-02, with the labels that each got.

#110 fix: 환경 주입 변수 수정
  src/main/java/com/dev/museummate/utils/MailUtils.java
Labels: Type: 🚀 Merge

#106 94 전시 리뷰 상세 조회 기능
  src/main/java/com/dev/museummate/controller/ReviewController.java
  src/main/java/com/dev/museummate/domain/dto/review/GetReviewResponse.java
  src/main/java/com/dev/museummate/exception/ErrorCode.java
  src/main/java/com/dev/museummate/service/ReviewService.java
  src/test/java/com/dev/museummate/controller/ReviewControllerTest.java
Labels: Type: 🚀 Merge

#102 98 함께 전시 관람 신청 목록 조회
  src/main/java/com/dev/museummate/controller/GatheringController.java
  src/main/java/com/dev/museummate/domain/dto/gathering/GatheringResponse.java
  src/main/java/com/dev/museummate/domain/dto/gathering/ParticipantDto.java
  src/main/java/com/dev/museummate/domain/entity/GatheringEntity.java
  src/main/java/com/dev/museummate/domain/entity/ParticipantEntity.java
  src/main/java/com/dev/museummate/repository/ParticipantRepository.java
  src/main/java/com/dev/museummate/service/GatheringService.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
Labels: Type: 🚀 Merge, Status: 👀 In_Review

#104 103 함께 전시 관람 승인 기능
  src/main/java/com/dev/museummate/controller/GatheringController.java
  src/main/java/com/dev/museummate/domain/dto/gathering/GatheringPostRequest.java
  src/main/java/com/dev/museummate/domain/entity/GatheringEntity.java
  src/main/java/com/dev/museummate/domain/entity/ParticipantEntity.java
  src/main/java/com/dev/museummate/exception/ErrorCode.java
  src/main/java/com/dev/museummate/repository/ParticipantRepository.java
  src/main/java/com/dev/museummate/service/GatheringService.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
Labels: Type: 🚀 Merge

#115 95 전시 리뷰 수정 기능
  src/main/java/com/dev/museummate/MuseumMateApplication.java
  src/main/java/com/dev/museummate/controller/ReviewController.java
  src/main/java/com/dev/museummate/domain/dto/review/EditReviewRequest.java
  src/main/java/com/dev/museummate/domain/dto/review/EditReviewResponse.java
  src/main/java/com/dev/museummate/domain/entity/ReviewEntity.java
  src/main/java/com/dev/museummate/service/ReviewService.java
  src/test/java/com/dev/museummate/controller/ReviewControllerTest.java
  src/test/java/com/dev/museummate/fixture/UserEntityFixture.java
Labels: Type: 🚀 Merge

#114 113 함께 전시 관람 기능 신청 취소 기능
  src/main/java/com/dev/museummate/controller/GatheringController.java
  src/main/java/com/dev/museummate/domain/entity/ParticipantEntity.java
  src/main/java/com/dev/museummate/repository/ParticipantRepository.java
  src/main/java/com/dev/museummate/service/GatheringService.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
Labels: Type: 🚀 Merge

#123 Chore: 브라켓 에러 수정
  src/main/java/com/dev/museummate/service/ReviewService.java
Labels: Type: 🚀 Merge, Type: 📝 Docs

#107 93 함께전시 모집글 조회 기능
  src/main/java/com/dev/museummate/controller/GatheringController.java
  src/main/java/com/dev/museummate/domain/dto/gathering/GatheringDto.java
  src/main/java/com/dev/museummate/domain/dto/gathering/GatheringParticipantResponse.java
  src/main/java/com/dev/museummate/domain/dto/gathering/GatheringResponse.java
  src/main/java/com/dev/museummate/domain/dto/gathering/ParticipantDto.java
  src/main/java/com/dev/museummate/repository/ParticipantRepository.java
  src/main/java/com/dev/museummate/service/GatheringService.java
  src/main/java/com/dev/museummate/service/ReviewService.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
  src/test/java/com/dev/museummate/controller/ReviewControllerTest.java
Labels: Type: 🚀 Merge

#120 96 전시 리뷰 삭제 기능
  src/main/java/com/dev/museummate/controller/ReviewController.java
  src/main/java/com/dev/museummate/domain/dto/review/DeleteReviewResponse.java
  src/main/java/com/dev/museummate/domain/dto/review/ReviewDto.java
  src/main/java/com/dev/museummate/domain/entity/ReviewEntity.java
  src/main/java/com/dev/museummate/service/ReviewService.java
  src/test/java/com/dev/museummate/controller/ReviewControllerTest.java
Labels: Type: 🚀 Merge

#130 fix: feild명 수정
  src/main/java/com/dev/museummate/domain/entity/ExhibitionEntity.java
Labels: Status: 🐞 Bug, Type: 🚀 Merge

#117 105 같이전시 모집글 수정/삭제 구현
  src/main/java/com/dev/museummate/controller/ExhibitionController.java
  src/main/java/com/dev/museummate/controller/GatheringController.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionDto.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionEditRequest.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionResponse.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionWriteRequest.java
  src/main/java/com/dev/museummate/domain/entity/GatheringEntity.java
  src/main/java/com/dev/museummate/repository/BookmarkRepository.java
  src/main/java/com/dev/museummate/service/AlarmScheduler.java
  src/main/java/com/dev/museummate/service/GatheringService.java
  src/test/java/com/dev/museummate/controller/ExhibitionControllerTest.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
  src/test/java/com/dev/museummate/controller/MyControllerTest.java
  src/test/java/com/dev/museummate/controller/ReviewControllerTest.java
Labels: Type: 🚀 Merge

#125 121 전시 리뷰 전체 조회 기능
  src/main/java/com/dev/museummate/controller/ReviewController.java
  src/main/java/com/dev/museummate/domain/dto/review/ReviewDto.java
  src/main/java/com/dev/museummate/domain/dto/review/ReviewPageResponse.java
  src/main/java/com/dev/museummate/repository/ReviewRepository.java
  src/main/java/com/dev/museummate/service/ReviewService.java
  src/test/java/com/dev/museummate/controller/ReviewControllerTest.java
Labels: Type: 🚀 Merge

#141 140 exhibition 관련 로직 리펙토링
  src/main/java/com/dev/museummate/controller/ExhibitionController.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionDto.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionEditRequest.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionResponse.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionWriteRequest.java
  src/main/java/com/dev/museummate/domain/entity/ExhibitionEntity.java
  src/main/java/com/dev/museummate/domain/entity/GalleryEntity.java
  src/main/java/com/dev/museummate/repository/GalleryRepository.java
  src/test/java/com/dev/museummate/controller/ExhibitionControllerTest.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
  src/test/java/com/dev/museummate/controller/MyControllerTest.java
  src/test/java/com/dev/museummate/controller/ReviewControllerTest.java
Labels: Type: 🚀 Merge, Type: 🔧 Refactor

#142 배포 수정 PR
  src/main/java/com/dev/museummate/controller/ExhibitionController.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionDto.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionEditRequest.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionResponse.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionWriteRequest.java
  src/main/java/com/dev/museummate/domain/entity/ExhibitionEntity.java
  src/main/java/com/dev/museummate/domain/entity/GalleryEntity.java
  src/main/java/com/dev/museummate/repository/GalleryRepository.java
  src/test/java/com/dev/museummate/controller/ExhibitionControllerTest.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
  src/test/java/com/dev/museummate/controller/MyControllerTest.java
  src/test/java/com/dev/museummate/controller/ReviewControllerTest.java
Labels: Type: 🚀 Merge

#143 122 함께 관람 모집 글 댓글기능
  src/main/java/com/dev/museummate/controller/GatheringController.java
  src/main/java/com/dev/museummate/domain/dto/gathering/CommentDto.java
  src/main/java/com/dev/museummate/domain/dto/gathering/CommentPostResponse.java
  src/main/java/com/dev/museummate/domain/dto/gathering/CommentRequest.java
  src/main/java/com/dev/museummate/domain/dto/gathering/CommentResponse.java
  src/main/java/com/dev/museummate/domain/entity/CommentEntity.java
  src/main/java/com/dev/museummate/repository/CommentRepository.java
  src/main/java/com/dev/museummate/service/GatheringService.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
  src/test/java/com/dev/museummate/service/GatheringServiceTest.java
Labels: Type: 🚀 Merge

#148 Fix: 리뷰 등록 기능에 쓰이는 dto 수정
  src/main/java/com/dev/museummate/domain/dto/review/WriteReviewResponse.java
  src/main/java/com/dev/museummate/security/SecurityConfiguration.java
  src/main/java/com/dev/museummate/service/ReviewService.java
Labels: Type: 🚀 Merge, Type: 🔧 Refactor

#149 147 exhibition 관련 누락 항목 추가 및 리팩토링
  src/main/java/com/dev/museummate/controller/ExhibitionController.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionDto.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionEditRequest.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionResponse.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionWriteRequest.java
  src/main/java/com/dev/museummate/domain/entity/ExhibitionEntity.java
  src/main/java/com/dev/museummate/repository/ExhibitionRepository.java
  src/main/java/com/dev/museummate/service/ExhibitionService.java
  src/test/java/com/dev/museummate/controller/ExhibitionControllerTest.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
Labels: Status: ✅ Done, Type: 🔧 Refactor

#160 158 함께 전시 관람 글 수정 기능 최대 인원수 변경 예외 추가
  src/main/java/com/dev/museummate/exception/ErrorCode.java
  src/main/java/com/dev/museummate/service/GatheringService.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
Labels: Type: 🚀 Merge, Status: 👀 In_Review

#144 134 social login 추가
  build.gradle
  src/main/java/com/dev/museummate/configuration/redis/entity/TokenEntity.java
  src/main/java/com/dev/museummate/configuration/redis/repository/TokenRepository.java
  src/main/java/com/dev/museummate/configuration/redis/service/TokenService.java
  src/main/java/com/dev/museummate/controller/UserController.java
  src/main/java/com/dev/museummate/controller/view/TestView.java
  src/main/java/com/dev/museummate/domain/UserRole.java
  src/main/java/com/dev/museummate/domain/entity/UserEntity.java
  src/main/java/com/dev/museummate/exception/AppException.java
  src/main/java/com/dev/museummate/exception/ErrorCode.java
  src/main/java/com/dev/museummate/repository/UserRepository.java
  src/main/java/com/dev/museummate/security/JwtFilter.java
  src/main/java/com/dev/museummate/security/SecurityConfiguration.java
  src/main/java/com/dev/museummate/security/oauth2/CustomOAuth2UserService.java
  src/main/java/com/dev/museummate/security/oauth2/OAuth2Attributes.java
  src/main/java/com/dev/museummate/security/oauth2/OAuth2FailureHandler.java
  src/main/java/com/dev/museummate/security/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/dev/museummate/security/oauth2/UserProfile.java
  src/main/java/com/dev/museummate/service/UserService.java
  src/main/java/com/dev/museummate/utils/CookieUtils.java
  src/main/java/com/dev/museummate/utils/HeaderUtils.java
  src/main/java/com/dev/museummate/utils/JwtUtils.java
  src/main/resources/application-jwt.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-springdoc.yml
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/test/java/com/dev/museummate/controller/ExhibitionControllerTest.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
  src/test/java/com/dev/museummate/security/SecurityFilterTest.java
Labels: Type: 🚀 Merge, Status: 👀 In_Review

#159 refactor: cors 설정 수정
  src/main/java/com/dev/museummate/configuration/WebMvcConfiguration.java
  src/main/java/com/dev/museummate/security/SecurityConfiguration.java
Labels: Type: 🚀 Merge, Type: 🔧 Refactor

#162 161 내가 참여한 함께 전시 관람 모집 글 조회
  src/main/java/com/dev/museummate/controller/MyController.java
  src/main/java/com/dev/museummate/repository/ParticipantRepository.java
  src/main/java/com/dev/museummate/service/MyService.java
  src/test/java/com/dev/museummate/controller/MyControllerTest.java
Labels: Type: 🚀 Merge, Status: 👀 In_Review

#169 docs: 4주차 위클리 문서 추가
  src/main/resources/static/weekly_log/[4주차]idea_14팀_진행상황_공유.md
Labels: Type: 🚀 Merge, Type: 📝 Docs

#166 164 내 정보 조회 기능
  src/main/java/com/dev/museummate/controller/MyController.java
  src/main/java/com/dev/museummate/domain/dto/user/UserDto.java
  src/main/java/com/dev/museummate/service/MyService.java
  src/test/java/com/dev/museummate/controller/MyControllerTest.java
  src/test/java/com/dev/museummate/service/MyServiceTest.java
Labels: Type: 🚀 Merge, Status: 👀 In_Review

#170 165 test code 수정 및 전체적인 리펙토링 진행
  build.gradle
  src/main/java/com/dev/museummate/configuration/redis/RedisConfig.java
  src/main/java/com/dev/museummate/configuration/redis/RedisDao.java
  src/main/java/com/dev/museummate/configuration/redis/entity/TokenEntity.java
  src/main/java/com/dev/museummate/configuration/redis/repository/TokenRepository.java
  src/main/java/com/dev/museummate/configuration/redis/service/TokenService.java
  src/main/java/com/dev/museummate/controller/ExhibitionController.java
  src/main/java/com/dev/museummate/controller/GatheringController.java
  src/main/java/com/dev/museummate/controller/MyController.java
  src/main/java/com/dev/museummate/controller/ReviewController.java
  src/main/java/com/dev/museummate/controller/UserController.java
  src/main/java/com/dev/museummate/domain/dto/Response.java
  src/main/java/com/dev/museummate/domain/dto/SimpleMessageResponse.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionEditRequest.java
  src/main/java/com/dev/museummate/domain/dto/user/UserTokenRequest.java
  src/main/java/com/dev/museummate/domain/entity/UserEntity.java
  src/main/java/com/dev/museummate/exception/AppException.java
  src/main/java/com/dev/museummate/exception/ErrorCode.java
  src/main/java/com/dev/museummate/exception/ExceptionManager.java
  src/main/java/com/dev/museummate/security/CustomAccessDeniedHandler.java
  src/main/java/com/dev/museummate/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/dev/museummate/security/JwtExceptionFilter.java
  src/main/java/com/dev/museummate/security/JwtFilter.java
  src/main/java/com/dev/museummate/security/SecurityConfiguration.java
  src/main/java/com/dev/museummate/security/oauth2/CustomOAuth2UserService.java
  src/main/java/com/dev/museummate/security/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/dev/museummate/service/ExhibitionService.java
  src/main/java/com/dev/museummate/service/UserService.java
  src/main/java/com/dev/museummate/utils/CookieUtils.java
  src/main/java/com/dev/museummate/utils/HeaderUtils.java
  src/main/resources/application-jwt.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/test/java/com/dev/museummate/controller/ExhibitionControllerTest.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
  src/test/java/com/dev/museummate/controller/ReviewControllerTest.java
  src/test/java/com/dev/museummate/controller/UserControllerTest.java
  src/test/java/com/dev/museummate/security/SecurityFilterTest.java
  src/test/java/com/dev/museummate/service/GatheringServiceTest.java
Labels: Type: 🚀 Merge, Status: 👀 In_Review, Type: 🔧 Refactor

#172 chore: redis 환경변수 수정
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
Labels: Status: ✅ Done

#174 fix: detailInfoUrl 추가
  src/main/java/com/dev/museummate/controller/ExhibitionController.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionDto.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionEditRequest.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionResponse.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionWriteRequest.java
  src/main/java/com/dev/museummate/domain/entity/ExhibitionEntity.java
Labels: Status: ✅ Done

#180 175 리뷰 기능 리팩토링
  src/main/java/com/dev/museummate/domain/dto/review/ReviewDto.java
  src/main/java/com/dev/museummate/domain/entity/ReviewEntity.java
  src/main/java/com/dev/museummate/service/ReviewService.java
Labels: Type: 🚀 Merge

#197 feat: 신청,승인 모집글 조회 기능 추가
  src/main/java/com/dev/museummate/controller/MyController.java
  src/main/java/com/dev/museummate/repository/ParticipantRepository.java
  src/main/java/com/dev/museummate/service/MyService.java
Labels: Type: 🚀 Merge, Status: 👀 In_Review

#199 feat: 신청 승인 알람 기능 추가
  src/main/java/com/dev/museummate/service/GatheringService.java
Labels: Type: 🚀 Merge, Status: 👀 In_Review

#214 이미지를 S3로 저장하는 기능 구현
  build.gradle
  src/main/java/com/dev/museummate/MuseumMateApplication.java
  src/main/java/com/dev/museummate/configuration/AwsS3Configuration.java
  src/main/java/com/dev/museummate/controller/ExhibitionImageController.java
  src/main/java/com/dev/museummate/domain/entity/ExhibitionEntity.java
  src/main/java/com/dev/museummate/service/ExhibitionImageService.java
  src/main/resources/application.yml
Labels: Status: ✅ Done

#215 Chore: 사용하지 않는 메서드 주석처리
  src/main/java/com/dev/museummate/service/ExhibitionImageService.java
Labels: Type: 🚀 Merge
