Repository Museum-Mate/museum-mate-be, pull requests merged in 2023-01, with the labels that each got.

#44 39 1주차 팀 위클리 공유
  README.md
  src/main/resources/static/weekly_log/[1주차]idea_14팀_진행상황_공유.md
Labels: Type: 🚀 Merge, Type: 📝 Docs

#49 47 swagger 추가 작업
  build.gradle
  src/main/java/com/dev/museummate/configuration/SwaggerConfiguration.java
  src/main/resources/application.yml
Labels: Type: 🚀 Merge, Type: ⚙️ Setting

#48 46 전체적인 dto layer 사용 및 lombok 리펙토링 작업
  src/main/java/com/dev/museummate/controller/ExampleController.java
  src/main/java/com/dev/museummate/controller/ExhibitionController.java
  src/main/java/com/dev/museummate/controller/UserController.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/BookmarkAddResponse.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/BookmarkDto.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionDto.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionResponse.java
  src/main/java/com/dev/museummate/domain/dto/user/UserDto.java
  src/main/java/com/dev/museummate/domain/dto/user/UserJoinRequest.java
  src/main/java/com/dev/museummate/domain/dto/user/UserLoginRequest.java
  src/main/java/com/dev/museummate/domain/dto/user/UserLoginResponse.java
  src/main/java/com/dev/museummate/domain/dto/user/UserReissueRequest.java
  src/main/java/com/dev/museummate/domain/entity/BookmarkEntity.java
  src/main/java/com/dev/museummate/domain/entity/ExhibitionEntity.java
  src/main/java/com/dev/museummate/domain/entity/GalleryEntity.java
  src/main/java/com/dev/museummate/domain/entity/UserEntity.java
  src/main/java/com/dev/museummate/security/SecurityConfiguration.java
  src/main/java/com/dev/museummate/service/ExhibitionService.java
  src/main/java/com/dev/museummate/service/UserService.java
  src/test/java/com/dev/museummate/controller/ExhibitionControllerTest.java
Labels: Type: 🚀 Merge, Type: 🔧 Refactor

#42 13 전시 목록 조회
  src/main/java/com/dev/museummate/controller/ExhibitionController.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionResponse.java
  src/main/java/com/dev/museummate/exception/ExhibitionException.java
  src/main/java/com/dev/museummate/repository/ExhibitionRepository.java
  src/main/java/com/dev/museummate/service/ExhibitionService.java
  src/test/java/com/dev/museummate/controller/ExhibitionControllerTest.java
Labels: Type: 🚀 Merge

#73 72 db insert query 작성
  src/main/resources/static/sql/CreateTable.sql
Labels: Type: 🚀 Merge, Type: ⚙️ Setting

#80 docs: 2주차 위클리 문서 추가
  src/main/resources/static/weekly_log/[2주차]idea_14팀_진행상황_공유.md
Labels: Type: 🚀 Merge, Type: 📝 Docs

#84 Bug: of 메소드 매개변수 수정
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionResponse.java
Labels: Type: 🚀 Merge

#77 전시 알람 기능
  build.gradle
  src/main/java/com/dev/museummate/configuration/SchedulerConfiguration.java
  src/main/java/com/dev/museummate/controller/MyController.java
  src/main/java/com/dev/museummate/domain/AlarmType.java
  src/main/java/com/dev/museummate/domain/dto/alarm/AlarmDto.java
  src/main/java/com/dev/museummate/domain/dto/alarm/AlarmResponse.java
  src/main/java/com/dev/museummate/domain/entity/AlarmEntity.java
  src/main/java/com/dev/museummate/repository/AlarmRepository.java
  src/main/java/com/dev/museummate/repository/BookmarkRepository.java
  src/main/java/com/dev/museummate/security/SecurityConfiguration.java
  src/main/java/com/dev/museummate/service/AlarmScheduler.java
  src/main/java/com/dev/museummate/service/MyService.java
  src/main/java/com/dev/museummate/utils/MailUtils.java
  src/test/java/com/dev/museummate/controller/MyControllerTest.java
Labels: Type: 🚀 Merge

#79 74 이메일 인증기능
  build.gradle
  src/main/java/com/dev/museummate/controller/UserController.java
  src/main/java/com/dev/museummate/domain/dto/user/UserDto.java
  src/main/java/com/dev/museummate/domain/dto/user/UserMailRequest.java
  src/main/java/com/dev/museummate/domain/entity/UserEntity.java
  src/main/java/com/dev/museummate/exception/ErrorCode.java
  src/main/java/com/dev/museummate/security/SecurityConfiguration.java
  src/main/java/com/dev/museummate/service/MailService.java
  src/main/java/com/dev/museummate/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/templates/mail.html
  src/test/java/com/dev/museummate/controller/UserControllerTest.java
Labels: Type: 🚀 Merge

#86 85 전시회 수정 기능 api 구현
  src/main/java/com/dev/museummate/controller/ExhibitionController.java
  src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionEditRequest.java
  src/main/java/com/dev/museummate/exception/ErrorCode.java
  src/main/java/com/dev/museummate/service/ExhibitionService.java
  src/test/java/com/dev/museummate/controller/ExhibitionControllerTest.java
Labels: Type: 🚀 Merge

#89 87 전시 리뷰 등록 기능(이슈 재발행)
  src/main/java/com/dev/museummate/configuration/JpaAuditingConfiguration.java
  src/main/java/com/dev/museummate/controller/ReviewController.java
  src/main/java/com/dev/museummate/domain/dto/review/ReviewDto.java
  src/main/java/com/dev/museummate/domain/dto/review/WriteReviewRequest.java
  src/main/java/com/dev/museummate/domain/dto/review/WriteReviewResponse.java
  src/main/java/com/dev/museummate/domain/entity/AuditorAwareImpl.java
  src/main/java/com/dev/museummate/domain/entity/ReviewEntity.java
  src/main/java/com/dev/museummate/exception/ErrorCode.java
  src/main/java/com/dev/museummate/repository/ReviewRepository.java
  src/main/java/com/dev/museummate/service/ReviewService.java
  src/test/java/com/dev/museummate/controller/ReviewControllerTest.java
Labels: Type: 🚀 Merge

#90 88 함께 전시 관람 글 작성 기능 추가
  src/main/java/com/dev/museummate/controller/GatheringController.java
  src/main/java/com/dev/museummate/domain/dto/gathering/GatheringDto.java
  src/main/java/com/dev/museummate/domain/dto/gathering/GatheringPostRequest.java
  src/main/java/com/dev/museummate/domain/dto/gathering/GatheringPostResponse.java
  src/main/java/com/dev/museummate/domain/entity/CommentEntity.java
  src/main/java/com/dev/museummate/domain/entity/GatheringEntity.java
  src/main/java/com/dev/museummate/domain/entity/ParticipantEntity.java
  src/main/java/com/dev/museummate/repository/GatheringRepository.java
  src/main/java/com/dev/museummate/repository/ParticipantRepository.java
  src/main/java/com/dev/museummate/security/SecurityConfiguration.java
  src/main/java/com/dev/museummate/service/GatheringService.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
Labels: Type: 🚀 Merge

#97 91 함께 전시 관람 신청 기능
  src/main/java/com/dev/museummate/controller/GatheringController.java
  src/main/java/com/dev/museummate/domain/entity/CommentEntity.java
  src/main/java/com/dev/museummate/domain/entity/ParticipantEntity.java
  src/main/java/com/dev/museummate/exception/ErrorCode.java
  src/main/java/com/dev/museummate/repository/ParticipantRepository.java
  src/main/java/com/dev/museummate/service/GatheringService.java
  src/test/java/com/dev/museummate/controller/GatheringControllerTest.java
  src/test/java/com/dev/museummate/service/GatheringServiceTest.java
Labels: Type: 🚀 Merge
